name: Build and Publish Anaconda

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_conda_packages:
    name: Build conda on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          auto-update-conda: false
          auto-activate-base: true
          show-channel-urls: true

      - name: Create Conda Env
        run: |
          conda create -y -n buildenv python=${{ matrix.python-version }} pip
          conda config --set solver classic

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate buildenv
          pip install Cython requests ujson setuptools wheel
          conda install -y -c conda-forge conda-build conda-verify anaconda-client

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call C:\Miniconda3\Scripts\activate.bat buildenv
          pip install Cython requests ujson setuptools wheel
          conda install -y -c conda-forge conda-build conda-verify anaconda-client

      - name: Debug environment and config
        shell: bash
        if: runner.os != 'Windows'
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate buildenv
          conda info
          conda config --show
          conda list
          pwd && ls -la
          echo "### meta.yaml"
          cat meta.yaml || echo "Missing!"

      - name: Debug environment and config (Windows)
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          call C:\Miniconda3\Scripts\activate.bat buildenv
          conda info
          conda config --show
          conda list
          dir

      - name: Render meta.yaml
        if: runner.os != 'Windows'
        shell: bash
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate buildenv
          conda render . || true
          conda render . --output || true

      - name: Render meta.yaml (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call C:\Miniconda3\Scripts\activate.bat buildenv
          conda render . || exit /b 0
          conda render . --output || exit /b 0

      - name: Build with conda-build
        if: runner.os != 'Windows'
        shell: bash
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate buildenv
          conda build . -c conda-forge -c defaults --no-verify --no-test --no-anaconda-upload --keep-old-work

      - name: Build with conda-build (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call C:\Miniconda3\Scripts\activate.bat buildenv
          conda build . -c conda-forge -c defaults --no-verify --no-test --no-anaconda-upload --keep-old-work

      - name: Install macOS SDK (only on macOS)
        if: runner.os == 'macOS'
        run: |
          sudo mkdir -p /opt/MacOSX10.10.sdk
          sudo curl -L -o MacOSX10.10.sdk.tar.xz https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.10.sdk.tar.xz
          sudo tar -xJf MacOSX10.10.sdk.tar.xz -C /opt/

      - name: Set CONDA_BUILD_SYSROOT (only on macOS)
        if: runner.os == 'macOS'
        run: |
          echo "CONDA_BUILD_SYSROOT: /opt/MacOSX10.10.sdk # [osx]" > conda_build_config.yaml

      - name: Build and upload the conda packages
        uses: uibcdf/action-build-and-upload-conda-packages@v1.2.0
        with:
          meta_yaml_dir: .
          overwrite: False
          python-version: ${{ matrix.python-version }}
          user: lucit
          label: main
          token: ${{ secrets.ANACONDA_API_TOKEN }}
